### PR TITLE
Refactor Source Code

### PR DESCRIPTION
**Pull request by aaghamohammadi**
I have refactored two files: ```cli.py``` and ```report.py```.

### CODE REVIEW

**Comment by EvanKepner** [comment]
@aaghamohammadi thanks for submitting the PR, are there planned functional changed/features based off of this refactor or is this maintenance only?

**Comment by aaghamohammadi** [comment]
Hi @EvanKepner 

This is just maintenance.

**Comment by EvanKepner** [comment]
Sweet, thanks for identifying some improvement areas, maintenance patches are under-appreciated. CI is green so this should be good to go, I'll likely have some time this weekend to take a look. Be sure to add yourself to the contributors section if you'd like: https://github.com/EvanKepner/mutatest/blob/master/AUTHORS.rst#contributors

**Comment by aaghamohammadi** [comment]
Sure,
Thanks, I've added my name.

**Comment by EvanKepner** [comment]
Released in: https://github.com/EvanKepner/mutatest/releases/tag/3.0.2 and available on pypi now, it should hit conda within a day or so.

**Pull request merged**
